# Foldable Sections

A foldable section can be created by placing text between two sets of three colons (`:::`) and specifying the `.foldable` class between two curly braces. An example is shown below.

    ::: {.foldable}
    This is a foldable section.
    :::

This creates the following foldable section:

::: {.foldable}
This is a foldable section.
:::


We have had some issues with multiple foldables in the past, so I include another one just for testing, and to show a 'multi-line' foldable with a different opening text.

::: {.foldable}
**ROAR**

samantha Dec 2013

The Lion & the Lamb And so the lion fell in love with the lamb She thought she had the upper hand But fate got in the way And the lion had nothing to say So they began a life together Determined to last forever For their love was stronger than you would believe So intense it almost decieves But the lion couldn't overcome All the obstacles to be with the one He left the lamb with tears in her eyes And wouldn't return despite her tries Now the lamb couldn't comprehend Why the lion wouldn't spend A life time with her by his side the lion and his stupid pride But the lion soon came to regret The fact that he could ever let His precious lamb get away And now the lion knew what to say He needed his lamb and needed her bad See he missed the love that they had But the lamb did not forgive All that the lion did But she loved her lion, she couldn't deny Even if she couldn't explain why And so the lion fell in love with the lamb Stupid lion, stupid lamb

From: <https://hellopoetry.com/words/lion/>

(we warned you)
:::

That's foldables for ya.

## Content types

Can they contain:

Inline r code?:

::: {.foldable}
let's try some `r 2+2`
:::


Footnotes like this one?^[I'm a footnote]

::: {.foldable}
Here comes a footnote.^[I'm a footnote]
:::


itemized lists?:

::: {.foldable}
Here comes a list

- item one
- item two
   - second level
:::

Html commented out text?:

::: {.foldable}
<!-- html comment thing -->
more text
:::

Latex math bits like "$x^2$?"?:

::: {.foldable}
trying ... $x^2$?
:::
