---
title: "Bookdown Template"
author: "Rethink Priorities"
bibliography: ["assets/bib/book.bib"]
always_allow_html: yes
link-citations: yes
github-repo: rethinkpriorities/bookdown-template
description: "The Rethink Priorities bookdown template"
site: bookdown::bookdown_site #this line is necessary to knit on David's machine
---


# About {.unnumbered}

This book is a bookdown template to be used for various projects of the Rethink Priorities survey team. The main goal of this book is to serve as a skeleton project that can be copied and used in other projects. Additionally, it contains some chapters that serve as tutorials for different features of this bookdown format.

You can find other content that will be helpful across bookdowns in the `main,R`, `index.Rmd` files in our other bookdowns, and `support`, `code`, and `assets` folders within these. 


#### Contributions {.unnumbered}

Please add yourself to the list below to acknowledge your contributions.

-   Willem Sleegers: [willem\@rethinkpriorities.org](mailto:willem@rethinkpriorities.org)

-   David Reinstein: [dreinstein\@rethinkpriorities.org](mailto:dreinstein@rethinkpriorities.org)
