# Foldable Sections

Our bookdown template supports foldable sections by means of custom blocks and custom code. Note that this means this feature is not supported out of the box and that some setup is necessary if you start with a fresh install of the `bookdown` format. It is recommended to clone the files of this template so that you don't have to worry about it.

A foldable section can be created by placing text between two sets of three colons (`:::`) and specifying the `.foldable` class between two curly braces. In addition, you should add a line of HTML code to add a button that folds and unfolds the section. An example is shown below.

    ::: {.foldable}
    <button class="fold-button">Show me more</button>

    This is a foldable section.
    :::

This creates the following foldable section:

::: foldable
<button class="fold-button">  Show me more  </button>

This is a foldable section.
:::

You can specify which text the button shows initially, but once you click on the button it will show "Show me less". This text could be changed to something else in the `header.html` file that can be found in the `html` folder of the `assets` folder.

The reason you have to specify the button itself is because of performance reasons. By putting the HTML code into the section itself, the text will be immediately shown to the user when a page is loaded. If we add the button using JavaScript, the label will initially not be shown and only show up after some (variable) time when the page is first opened.

\

We have had some issues with multiple foldables in the past, so I include another one just for testing, and to show a 'multi-line' foldable with a different opening text.

::: foldable
<button class="fold-button">  Do not open this foldable unless you want to hear about a lion  </button>

**ROAR**

samantha Dec 2013

The Lion & the Lamb And so the lion fell in love with the lamb She thought she had the upper hand But fate got in the way And the lion had nothing to say So they began a life together Determined to last forever For their love was stronger than you would believe So intense it almost decieves But the lion couldn't overcome All the obstacles to be with the one He left the lamb with tears in her eyes And wouldn't return despite her tries Now the lamb couldn't comprehend Why the lion wouldn't spend A life time with her by his side the lion and his stupid pride But the lion soon came to regret The fact that he could ever let His precious lamb get away And now the lion knew what to say He needed his lamb and needed her bad See he missed the love that they had But the lamb did not forgive All that the lion did But she loved her lion, she couldn't deny Even if she couldn't explain why And so the lion fell in love with the lamb Stupid lion, stupid lamb

From: <https://hellopoetry.com/words/lion/>

(we warned you)
:::

That's foldables for ya.

## What kind of content can foldables containt

Can they contain:

Inline r code?:

::: {.foldable}
 <button class='fold-button'>try inline r code</button>

 let's try some `r 2+2`
:::


Footnotes?:

::: {.foldable}
<button class='fold-button'>try a footnote</button>

Here comes a footnote.^[I'm a footnote]
:::


Html commented out text?:

::: {.foldable}
<button class='fold-button'>try html comment</button>
<!-- html comment thing -->
more text
:::

Latex math bits like "$x^2$?"?:

::: {.foldable}
 <button class='fold-button'>try latex</button>
trying ... $x^2$?
:::
